### ISSUE TITLE
Block structure

### ISSUE THREAD

**Issue by Jonathan50** [Jonathan50/do-it#5]
do-it should have [block structure](https://en.wikipedia.org/wiki/Block_structure)

Possibilities:
* Make begin create a new scope (this will be bad if I add macros)
* Add a new block special form that introduces a new scope

**Comment by BookOwl** [comment]
How about a `block` special form that works just likes, `begin`, except that it creates a new scope?

**Comment by Jonathan50** [comment]
That's what I meant by the second possibility.

**Comment by Jonathan50** [comment]
I could leave popping the local variables to the end of the procedure, but then the rest of the procedure would be taking more stack space than necessary&hellip; I should add another item to the *stack* at the start of a block but rather than it starting at 0 have it start at the same

**Comment by Jonathan50** [comment]
I've implemented a block special form on the `block` branch and it works

**Comment by Jonathan50** [comment]
Added with #6
